### PR TITLE
Update uglify to uglify es

### PR DESCRIPTION
**Pull request by conorluddy**

### CODE REVIEW

**Comment by rbelling** [comment]
Hey @conorluddy could you confirm that the above change works when running the page on a iOS8 device?

**Comment by conorluddy** [comment]
Good catch, @rbelling. This change was to stop swig-minify from crashing when it hit 'let', but if we're supporting iOS8 then maybe we can't go down this route yet...

@njprrogers – any thoughts? 

screen shot 2017-08-18 at 11 30 48

**Comment by conorluddy** [comment]
FYI - On BrowserStack, iOS9 also seems to crap out at `let`

**Comment by rbelling** [comment]
Such a shame. If it was an iOS8 only limitation, we might say go with it, but with iOS9 in the way...

**Comment by conorluddy** [comment]
Maybe gulp-uglify had the right idea after all :)  Let ignore this PR

**Pull request closed without merging**
